unbind C-b
set -g prefix C-a
bind C-a send-prefix

# reload
bind r source-file $XDG_CONFIG_HOME/tmux/tmux.conf \; display "sourced ${XDG_CONFIG_HOME}/tmux/tmux.conf"

# session: rename
bind N command-prompt 'rename-session -- %%'

# window: switch
bind -r , selectw -p
bind -r . selectw -n
# window: swap
bind -r < swapw -t -1
bind -r > swapw -t +1
# window: rename
bind n command-prompt 'rename-window -- %%'

# pane: split
bind - splitw -v
bind | splitw -h
# pane: switch
bind -r h selectp -L
bind -r j selectp -D
bind -r k selectp -U
bind -r l selectp -R
# pane: swap
bind -r [ swapp -U
bind -r ] swapp -D
# pane: resize
bind -r H resizep -L 2
bind -r J resizep -D 2
bind -r K resizep -U 2
bind -r L resizep -R 2

# select and copy (yank)
bind i copy-mode
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "\
  if type pbcopy >/dev/null 2>&1; then \
    pbcopy; \
  elif type wl-copy >/dev/null 2>&1; then \
    wl-copy; \
  elif type xclip >/dev/null 2>&1; then \
    xclip -selection clipboard -i; \
  elif type clip.exe >/dev/null 2>&1; then \
    clip.exe; \
  fi"

# `tmux show -s` to show all server options
# `tmux show -g` to show all global options

set -sa terminal-features ',xterm-ghostty:RGB'
set -sa terminal-features ',xterm-ghostty:usstyle'

set -g allow-passthrough on
set -g default-terminal 'tmux-256color'
set -g display-time 20000
set -g history-limit 100000
set -g mode-keys vi
set -g mouse on
set -g pane-active-border-style fg=colour9,bg=colour0
set -g pane-border-style fg=colour12,bg=colour0
set -g renumber-windows on
set -g status-interval 5
set -g status-justify left
set -g status-left '#[fg=colour0,bold]#[bg=colour3] #H #[bg=colour4] #S #[bg=#373b41] '
set -g status-left-length 40
set -g status-right-length 40
set -g status-style fg=colour7,bg='#373b41'
set -g window-status-current-format '#[fg=colour0,bg=colour2,bold] #I #W '
set -g window-status-format '#[fg=colour0,bg=colour7,bold] #I #W '
set -g window-status-separator ' '

set -g status-right '#[fg=colour0,bold]#[bg=colour4]'
set -ga status-right ' #(~/.config/tmux/monitor_network.sh) '
set -ga status-right ' #(~/.config/tmux/monitor_battery.sh) '
set -ga status-right '#[fg=colour0,bold]#[bg=colour3]'
set -ga status-right ' %a %b %d %I:%M %p '

set -s escape-time 10
set -s focus-events on
